services:
  - type: web
    name: voice-biometrics
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: RENDER_DISK_PATH
        value: "."
